M48
; DRILL file {KiCad 9.0.9-9.0.9~ubuntu24.04.1} date 2026-10-09T05:53:30+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-09T05:53:30+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.9-9.0.9~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.600
%
G90
G05
T1
X-21.0Y33.5
X-21.0Y-33.5
X21.0Y24.77
X21.0Y-33.5
M30
