"""Single source of truth for wall-plate geometry (mm).

Coordinates: X = width, Y = height (up), Z = out of the wall.
z = 0 is the wall surface, plate face at z = PT, z < 0 is inside the box (MAINS SIDE).

Tags:
  MEASURE   placeholder - replace with a caliper reading recorded in
            docs/MEASUREMENTS.md before printing anything final.
  DATASHEET value that must come from a cited datasheet (see docs/BOM.md).
  derived   computed below - do not edit, change the inputs instead.

v0.2 is two printed parts (DESIGN D-12, D-13..D-17):
  insert  (insert.py)  all barrier geometry: remote pocket, switch well, collar
                       flange, PSU rails. UL94 V-0 filament, printed floor-down.
  trim    (trim.py)    face, MSR-2 / SHT45 bays, vents. Any filament, face-down.
"""
from math import sqrt, hypot

# ---- trim plate ----
PW, PH, PT, PR = 82.0, 150.0, 13.0, 6.0   # width, height, proud of wall, corner radius
SKIN = 2.0                                # face/side wall of the hollow trim
FACE_CHAMFER = 1.2

# ---- NA single-gang device box ----
BOX_W, BOX_H = 50.8, 76.2                 # 2" x 3" opening
BOX_D = 63.5                              # MEASURE (2.5" assumed), per room
SCREW_PITCH = 83.3                        # #6-32 device ears, 3-9/32"
SCREW_D, SCREW_HEAD_D = 3.8, 8.0

# ---- IKEA BILRESA scroll wheel remote (kept intact, batteries in) ----
B_W, B_H, B_D = 42.0, 70.0, 20.0          # MEASURE stadium outline + depth
B_PROUD = 2.0
CLR = 0.6
POCKET_WALL = 1.6                         # pocket shell = mains barrier
SEAT_T = 2.5                              # minimum material under the remote seat
STEEL = (20.5, 12.5, 0.8)                 # MEASURE steel magnet target recess (w, h, depth)
STEEL_Y = -18.0

# ---- emergency rocker: Bulgin/Arcolectric C1300AABBEN602A ----
SW_CUT = (27.3, 12.3)                     # DATASHEET panel cutout
SW_PANEL_T = 1.5                          # MEASURE/DATASHEET snap-in panel range (print coupon_rocker)
SW_BEZEL = (31.0, 16.0)                   # MEASURE
SW_ROCKER_H = 10.0                        # MEASURE bezel + rocker height above panel
SW_BODY = (26.0, 11.5, 24.0)              # MEASURE body incl. 6.3 mm tabs
SW_Y = 18.0
SW_LATCH_CLR = 1.5                        # room for the snap latches under the panel

# ---- PSU carrier PCB (KiCad project in pcb/kicad) ----
PCB = (42.0, 44.0, 1.6)                   # D-14: 42 wide keeps 2 mm rail strips clear of the 37 mm IRM
PCB_TOP_GAP = 4.0                         # PCB top edge to rocker body
PCB_STUB_CLR = 2.5                        # THT lead stubs on the PCB back (trim leads to <= 2 mm)
IRM = (37.0, 24.0, 15.0)                  # DATASHEET Mean Well IRM-03-5 body (IRM-03-SPEC 2025-08-08)
IRM_KEEPOUT = 2.0                         # no copper/parts within this of the rail edges
RAIL_ENGAGE = 1.25                        # PCB edge depth in the groove
RAIL_CLR = 0.3                            # groove clearance (each side)
RAIL_W = 3.0                              # rail wall outside the PCB edge
RAIL_LIP = 2.0                            # lip under the PCB front (component side)
STOP_T = 1.6                              # end stop above the PCB top edge
GABLE_PITCH = 6.0                         # 45-degree self-supporting roof over the PCB back
# KiCad board coordinates (front view, Y up) of the parts the CAD cares about.
# The board's F side faces INTO the box, so in the room frame KiCad +x -> room -x.
# Source: pcb/SPEC.md layout table (generated by pcb/tools/parts.py).
PCB_SLOT_X = (-7.5, -5.5)                 # isolation slot notch from the top edge (KiCad x)
PCB_SLOT_YEND = -8.0
PCB_J2_X = -13.25                         # JST-XH 5 V out, KiCad x (pads -12 / -14.5) -> room +13.25
PCB_J1_ENTRY_Y = 20.7                     # J1 wire-entry face, board Yup (pigtails leave towards the rocker)
J1_BEND_MIN = 5.0                         # room for the mains pigtails to turn back into the box

# ---- insert (box side, V-0) ----
PLUG_CLR = 0.75                           # insert body to box wall, each side
PLUG_R = 3.0
COLLAR_LIP = 1.25                         # flat seal band on the wall beyond the box edge
FLANGE = 3.0                              # flange beyond the island, clamped by the trim
ISLAND_RIM = 1.2                          # visible insert rim around pocket + scoops
ISLAND_R = 6.0
BOSS_R = 4.0                              # screw boss on the insert
KEY_D, KEY_H, KEY_CLR = 3.0, 1.0, 0.15    # locating pins insert -> trim (asymmetric = keyed)
KEY_POS = ((25.0, 30.0), (-25.0, -22.0))
SPLIT_CLR = 0.25                          # trim to insert clearance
SCOOP = (4.5, 12.0, 7.0)                  # finger scoop ellipsoid radii (x, y, z)
SCOOP_ZC = PT + 2.5                       # scoop centre height
PASS_D = 3.5                              # 5 V lead pass-through (the only barrier opening)
PASS_X, PASS_Y = 21.5, 31.0               # vertical leg position (room frame, J2 side: -PCB_J2_X > 0)
BARRIER_MIN = 1.6                         # thinnest barrier wall allowed
V0_RATED_T = 1.5                          # DATASHEET thickness at which the chosen filament is UL94 V-0

# ---- Apollo MSR-2 (bare board, out of its case) ----
MSR = (40.0, 24.0, 10.0)                  # MEASURE envelope
RADAR_WALL = 1.2
LUX_POS = (12.0, 0.0)                     # MEASURE light sensor offset from bay centre

# ---- SHT45 breakout tab ----
SHT = (12.0, 8.0, 4.0)                    # MEASURE
SHT_Y = -62.0

# ================= derived =================
SEAT_Z = PT + B_PROUD - B_D               # remote's back rests here
POCKET_IN = (B_W + 2 * CLR, B_H + 2 * CLR)
POCKET_OUT = (POCKET_IN[0] + 2 * POCKET_WALL, POCKET_IN[1] + 2 * POCKET_WALL)
WELL_FLOOR_Z = SEAT_Z - SW_ROCKER_H       # top face of the switch panel
PANEL_BOT_Z = WELL_FLOOR_Z - SW_PANEL_T   # underside of the switch panel
WELL_IN = (SW_BEZEL[0] + 2 * CLR, SW_BEZEL[1] + 2 * CLR)
DECK_Z = PT - SKIN                        # insert flange top = trim face underside

# PSU carrier position: top edge PCB_TOP_GAP below the rocker body
SW_BODY_BOT_Y = SW_Y - SW_BODY[1] / 2
PCB_TOP_Y = SW_BODY_BOT_Y - PCB_TOP_GAP
PCB_Y = PCB_TOP_Y - PCB[1] / 2
PCB_BACK_Z = PANEL_BOT_Z - 2.0            # PCB back face (towards the plate)
PCB_FRONT_Z = PCB_BACK_Z - PCB[2]         # component side faces into the box
GABLE_VALLEY_Z = PCB_BACK_Z + PCB_STUB_CLR
GABLE_PEAK_Z = GABLE_VALLEY_Z + GABLE_PITCH / 2
Z_BOT = PCB_FRONT_Z - RAIL_CLR - RAIL_LIP # lowest point of the insert = print bed
PSU_X = PCB[0] / 2 + RAIL_W               # half width of the PSU block
PSU_Y0 = -(BOX_H / 2 - PLUG_CLR)          # bottom end of the rails (open: PCB slides in here)
PSU_Y1 = PCB_TOP_Y + RAIL_CLR + STOP_T    # top end stop

# insert outline
PLUG = (BOX_W - 2 * PLUG_CLR, BOX_H - 2 * PLUG_CLR)
SEAL = (BOX_W + 2 * COLLAR_LIP, BOX_H + 2 * COLLAR_LIP)
_sc_face = SCOOP[0] * sqrt(max(0.0, 1 - ((SCOOP_ZC - PT) / SCOOP[2]) ** 2))
SCOOP_X = POCKET_IN[0] / 2 + 0.6
ISLAND = (2 * (SCOOP_X + _sc_face + ISLAND_RIM), POCKET_OUT[1] + 2 * ISLAND_RIM)
FLANGE_OUT = (ISLAND[0] + 2 * FLANGE, ISLAND[1] + 2 * FLANGE)
# depth of the 45-degree taper that carries the flange underside (plug corner -> pocket shell)
_r = POCKET_OUT[0] / 2
_cx, _cy = PLUG[0] / 2 - PLUG_R * (1 - 0.7071), PLUG[1] / 2 - PLUG_R * (1 - 0.7071)
TAPER_D = round(hypot(_cx, _cy - (POCKET_OUT[1] / 2 - _r)) - _r + 0.6, 1)

# MSR-2 bay sits just above the top screw (boss + countersink), SHT45 bay as before
MSR_Y = SCREW_PITCH / 2 + max(BOSS_R + SPLIT_CLR, SCREW_HEAD_D / 2 + 1.0) + MSR[1] / 2 + CLR
